version: "3.7"

services:
  node-srv:
    build: node-srv
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: yandex/clickhouse-server:20.4
    healthcheck:
      test: pwd || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - 8123
      - 9000
    volumes:
      - ./db:/etc/clickhouse-server
